[package]
name = "risc0-digital-signature-methods-inner"
version = "0.1.0"
edition = "2021"

[build-dependencies]
risc0-build = "0.7.0-dev.1"

[target.riscv32im-unknown-none-elf.dependencies]
risc0-digital-signature-shared = { path = "../../shared" }
risc0-zkvm-guest = "0.7.0-dev.1"