[workspace]

[package]
name = "zk-poc-methods-guest"
version = "0.12.0"
edition = "2021"

[dependencies]
zk-poc-core = { path = "../../core" }
risc0-zkvm = { version = "0.12", default-features = false }

[profile.release]
lto = true
opt-level = "z"

[build-dependencies]
risc0-build = "0.12"
